rules:
  - http:
      path:
        - path: "/api/v1"
          path_type: "Prefix"
          backend:
            service:
              name: "ondaum-server"
              port:
                number: 8080
              timeout: 86400
        - path: "/"
          path_type: "Prefix"
          backend:
            service:
              name: "ondaum-client"
              port:
                number: 80
              timeout: 300